### ISSUE TITLE
Lỗi rồi ad ơi,

### ISSUE THREAD

**Issue by HoanDao** [zuydd/match-quest#1]
Fix code đc ko ạ

Nó lỗi này

============== Chạy tài khoản 3 | Phạm Mỹ Loan 🦴 ==============
[ No 3 _ ID: 6773462870 _ IP: 103.176.112.53 ] unable to verify the first certificate
[ No 3 _ ID: 6773462870 _ IP: 103.176.112.53 ] Quá trình đăng nhập thất bại, vui lòng kiểm tra lại thông tin tài khoản (có thể cần phải lấy mới query_id). Hệ thống sẽ thử đăng nhập lại sau 60s

**Comment by zuydd** [comment]
đã fix, tải bản mới nhất v0.0.7 nhé
